<?php
session_start();
if (!isset($_SESSION['user_id'])) {
    header('Location: index.html');
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Workout Planner</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <nav class="navbar">
        <div class="nav-container">
            <h1 class="nav-logo">Workout Planner</h1>
            <ul class="nav-menu">
                <li class="nav-item"><a href="home.php" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="workout.php" class="nav-link active">Workout Planner</a></li>
                <li class="nav-item"><a href="auth.php?action=logout" class="nav-link">Logout</a></li>
            </ul>
        </div>
    </nav>
    
    <div class="container">
        <h2>Weekly Workout Planner</h2>
        <div class="calendar" id="workout-calendar">
            <!-- Calendar will be generated by JavaScript -->
        </div>
        
        <!-- Workout Modal -->
        <div id="workout-modal" class="modal">
            <div class="modal-content">
                <span class="close">&times;</span>
                <h3>Add Workout for <span id="selected-day"></span></h3>
                <form id="workout-form">
                    <input type="hidden" id="day-index" name="day-index">
                    <div class="form-group">
                        <label for="workout-name">Workout Name</label>
                        <input type="text" id="workout-name" name="workout-name" required>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn">Save Workout</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        // Days of the week
        const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
        let workouts = [];
        
        // Function to generate calendar
        function generateCalendar() {
            const calendar = document.getElementById('workout-calendar');
            calendar.innerHTML = '';
            
            days.forEach((day, index) => {
                const dayElement = document.createElement('div');
                dayElement.className = 'calendar-day';
                
                const dayHeader = document.createElement('div');
                dayHeader.className = 'day-header';
                dayHeader.textContent = day;
                dayElement.appendChild(dayHeader);
                
                const workoutList = document.createElement('div');
                workoutList.className = 'workout-list';
                workoutList.id = `day-${index}`;
                
                // Add workouts for this day if they exist
                if (workouts[index] && workouts[index].length > 0) {
                    workouts[index].forEach(workout => {
                        const workoutTag = document.createElement('div');
                        workoutTag.className = 'workout-tag';
                        workoutTag.textContent = workout;
                        workoutList.appendChild(workoutTag);
                    });
                }
                
                dayElement.appendChild(workoutList);
                
                const addButton = document.createElement('button');
                addButton.className = 'add-workout-btn';
                addButton.textContent = '+ Add Workout';
                addButton.onclick = function() {
                    openWorkoutModal(day, index);
                };
                dayElement.appendChild(addButton);
                
                calendar.appendChild(dayElement);
            });
        }
        
        // Function to open workout modal
        function openWorkoutModal(day, index) {
            document.getElementById('selected-day').textContent = day;
            document.getElementById('day-index').value = index;
            document.getElementById('workout-name').value = '';
            document.getElementById('workout-modal').style.display = 'block';
        }
        
        // Close modal when clicking on X
        document.querySelector('.close').onclick = function() {
            document.getElementById('workout-modal').style.display = 'none';
        };
        
        // Close modal when clicking outside of it
        window.onclick = function(event) {
            const modal = document.getElementById('workout-modal');
            if (event.target === modal) {
                modal.style.display = 'none';
            }
        };
        
        // Handle workout form submission
        document.getElementById('workout-form').addEventListener('submit', function(e) {
            e.preventDefault();
            
            const dayIndex = document.getElementById('day-index').value;
            const workoutName = document.getElementById('workout-name').value;
            
            // Create AJAX request to save workout
            const xhr = new XMLHttpRequest();
            xhr.open('POST', 'workout_functions.php', true);
            xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
            
            xhr.onload = function() {
                if (this.status === 200) {
                    const response = JSON.parse(this.responseText);
                    if (response.success) {
                        // Update local workouts array
                        workouts = response.workouts;
                        // Regenerate calendar
                        generateCalendar();
                        // Close modal
                        document.getElementById('workout-modal').style.display = 'none';
                    } else {
                        alert('Error saving workout: ' + response.message);
                    }
                }
            };
            
            xhr.send(`action=add_workout&day_index=${dayIndex}&workout_name=${encodeURIComponent(workoutName)}`);
        });
        
        // Load workouts when page loads
        window.onload = function() {
            // Create AJAX request to get workouts
            const xhr = new XMLHttpRequest();
            xhr.open('GET', 'workout_functions.php?action=get_workouts', true);
            
            xhr.onload = function() {
                if (this.status === 200) {
                    const response = JSON.parse(this.responseText);
                    if (response.success) {
                        workouts = response.workouts;
                        generateCalendar();
                    } else {
                        alert('Error loading workouts: ' + response.message);
                    }
                }
            };
            
            xhr.send();
        };
    </script>
</body>
</html>

